### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [DimasSavchenko/Template-MoGo#1]
`14/09/2017`

1. Где-то намудрил с padding, не правильно срабатывает положение элемента http://joxi.ru/5mdQa37SkQdG62
1. Я бы рекомендовал всё таки поискать аналогичные `svg` или fa подключить и похожие на эти заюзать, png смотрится дешево. Так во всем проекте
1. Оно же не красиво, паддингов от слова нет, к кнопке не вплотную.. http://joxi.ru/p27oX35iodbwV2
1. Insta фотки скейлятся резко и дерзко, можно плавности дать?
1. Ты сейчас идеально нарезал картинки для блога, а что если я тебе дам их разной ширины ?
я про эти:
```
.footer-blog__img {
    height: 100%;
}
```
6. Модификатор юзается только в паре с `блоком` или `элементом`:
`class="footer__heading txt--up"`, тоесть, если у тебя модифицируется здесь блок `txt`, то нужно было писать `footer__heading txt txt--up`
7. А где бутстрап??
8. Ты используешь container бутстрапа, а потом перебиваешь его ради 10px, зачем??
9. Cклейка bg выглядит ужасно, может не надо его repeat?  http://joxi.ru/vAWyNp3C1xzwnm 
10.  По идеи у тебя основная единица это `blog__block`, а ты отступ задаешь декору. Это значит что без иконок пропадет важный отступ и blog сольется со следующей секцией, тебе ок?
11. 
```
.blog__icon {
    display: flex;
    padding-bottom: 120px;
}
```
12. там где ты мог бы просто задать display:block, ты используешь сложную структуру с flex, flex-direction..не уверен, что хорошая идея. Много движухи ради маленького блочка
```
.blog__date {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 25%;
    z-index: 3;
    background: #95e1d3;
    padding: 10px 15px;
    transform: translate(-25%, 0);
```
13. Тоже самое, `header__sub` пропадает и с ним уходит 90px отступа, хотя это отступ хедера
`header__sub txt--up`
14. Говорили о том, чтобы использовать тег для цитат
http://joxi.ru/ZrJpZ0Xf95ypJ2
15. Главный экран не фиксирован по высоте
16. Что я говорил про разный регистр? `collapseTwo`

Общее впечатление: 
> Со структурой уже лучше.
> Ты должен вглядываться в каждый пиксель, тут много моментов, которые визуально самого себя устраивать не должно.
> Уже вижу чуть БЭМа, но пока путаешься
> Ты сильно зациклен на flex, у тебя потом будут проблемы с `display, float, position`, потому что ты их даже не пытаешься понять использую универсальную отмычку от всего.
> `<html lang="zxx">` слушаешь других. Молодец :)

**Comment by DimasSavchenko** [comment]
1. Да, был padding, исправил на margin.
2. Если ты про значки поиска и корзины в хэдере, то у меня там fa и заюзаны:
    <ul class="nav__icon">
            <li class="icon__item"><a href="#" class="icon__link color--white"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
            <li class="icon__item"><a href="#" class="icon__link color--white"><i class="fa fa-search" aria-hidden="true"></i></a></li>
          </ul>
3. Добавил паддинги, вплотную к кнопке не становится.
4. Добавил плавности инста фоткам.
5. Оберну их в div и дам ему фиксированную ширину.
6. Класс txt--up - это общий класс для того, чтоб текст стал заглавными буквами:
    .txt--up {
	text-transform: uppercase;
}
7. Аккордеон на бутстрапе.
8. Класс container я использую для задания общей ширины и центрирования (не понял про 10px):
    .container {
	max-width: 1160px;
	margin: 0 auto;
}
9. Уменьшил padding.
10, 11. Согласен, дал блоку паддинг.
12. Упростил, сделал    display: block.
13. Задал отступ для хедера и отдельно для текста.
14. Добавил blockquote и cite.
15. Фиксирован:
    .hero .container {
	height: 100vh;
	min-height: 500px;
	position: relative;
}
16. Исправил.

**Comment by DimasSavchenko** [comment]
15. Фиксирован:
    .hero .container {
	height: 100vh;
	min-height: 500px;
	position: relative;
}
16. Согласен, исправил.
